version: '2'
distribution_spec:
  description: Use Cerebras for running LLM inference
  providers:
    inference:
    - remote::cerebras
    safety:
    - inline::llama-guard
    memory:
    - inline::faiss
    - remote::chromadb
    - remote::pgvector
    agents:
    - inline::meta-reference
    eval:
    - inline::meta-reference
    datasetio:
    - remote::huggingface
    - inline::localfs
    scoring:
    - inline::basic
    - inline::llm-as-judge
    - inline::braintrust
    telemetry:
    - inline::meta-reference
    tool_runtime:
    - remote::brave-search
    - remote::tavily-search
    - inline::code-interpreter
    - inline::memory-runtime
image_type: conda
